rootProject.name = "bgw"
include("bgw-gui")
include("bgw-examples")
include("bgw-examples:bgw-maumau-example")
include("bgw-examples:bgw-sudoku-example")
include("bgw-examples:bgw-tetris-example")
include("bgw-examples:bgw-docs-examples")
include("bgw-net:bgw-net-server")
include("bgw-net:bgw-net-client")
include("bgw-net:bgw-net-common")
