spring:
  security:
    oauth2:
      client:
        registration:
          gitlab:
            provider: gitlab
            client-name: GitLab
            clientId: ${GITLAB_CLIENT_ID}
            clientSecret: ${GITLAB_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirectUri:  "http://{baseHost}{basePort}{basePath}/login/oauth2/code/{registrationId}"
            scope: openid,email,profile
        provider:
          gitlab:
            authorization-uri: ${GITLAB_URL}/oauth/authorize
            token-uri: ${GITLAB_URL}/oauth/token
            user-info-uri: ${GITLAB_URL}/oauth/userinfo
            user-name-attribute: sub
            jwk-set-uri: ${GITLAB_URL}/oauth/discovery/keys
